arb-dir: assets/strings
template-arb-file: strings_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/presentation/common/localization
synthetic-package: true
use-escaping: true
