name: suances
description: "Application to manage purchase orders, suppliers, expenses and
  income of the restaurant"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.10
  cupertino_icons: ^1.0.6
  diacritic: ^0.1.5
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: any
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  provider: ^6.1.2
  responsive_framework: ^1.4.0
  share_plus: ^9.0.0
  sqflite: ^2.3.3+1
  universal_html: ^2.2.4
  uuid: ^4.4.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  faker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # flutter localizations
  assets:
    - assets/images/
    - assets/strings/

# -> dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/suances.jpeg
  web: false
  fullscreen: true

# -> dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/suances.jpeg
  min_sdk_android: 21
  background_color: "#ffffff"
  web:
    generate: true
    image_path: assets/images/suances.jpeg
    background_color: "#ffffff"
    theme_color: "#ffffff"
