name: suances
description: "Application to manage purchase orders, suppliers, expenses and
  income of the restaurant"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.7
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.1
  google_mlkit_text_recognition: ^0.14.0
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  responsive_framework: ^1.5.1
  share_plus: ^10.1.2
  sqflite: ^2.4.1
  universal_html: ^2.2.4
  uuid: ^4.5.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  faker: ^2.2.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # flutter localizations
  assets:
    - assets/images/
    - assets/strings/

# -> dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/suances.jpeg
  web: false
  fullscreen: true

# -> dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/suances.jpeg
  min_sdk_android: 21
  background_color: "#ffffff"
  web:
    generate: true
    image_path: assets/images/suances.jpeg
    background_color: "#ffffff"
    theme_color: "#ffffff"
