name: suances
description: "Application to manage purchase orders, suppliers, expenses and
  income of the restaurant"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.10
  cupertino_icons: ^1.0.6
  diacritic: ^0.1.5
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  uuid: ^4.4.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  faker: ^2.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # flutter localizations
  assets:
    - assets/images/
    - assets/strings/
